apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: $NAMESPACE
  name: $INGRESS
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "$SSL_TRUEFALSE"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "$SSL_TRUEFALSE"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "15"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "15"
spec:
  #### BIND TO NGINX FROM: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/cloud/deploy.yaml
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #       - $PRODUCTS_HOSTNAME
  #       - $DATA_HOSTNAME
  #     secretName: $TLS_SECRET
  rules:
    - host: $PRODUCTS_HOSTNAME
      http:
        paths:
          - path: $PRODUCTS_URI
            pathType: Prefix
            backend:
              service:
                name: $SERVICE
                port:
                  number: $PRODUCTS_PORT
    - host: $DATA_HOSTNAME
      http:
        paths:
          - path: $DATA_URI
            pathType: Prefix
            backend:
              service:
                name: $SERVICE
                port:
                  number: $DATA_PORT