apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: algorithmic-hue
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: $HOSTNAME_ROOT_PATH
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: $RUNPORT_WEB_SERVICE
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: data-access-service
                port:
                  number: $RUNPORT_DATA_ACCESS_SERVICE
